// Code generated by leia mod gomod; DO NOT EDIT.
module github.com/never-labs/leia-raylib

go 1.25.7

require (
	github.com/gen2brain/raylib-go/raylib v0.55.1
	github.com/never-labs/leia v0.0.0-20260601072313-1f1c04c2143e
)

require (
	github.com/ebitengine/purego v0.7.1 // indirect
	golang.org/x/arch v0.26.0 // indirect
	golang.org/x/exp v0.0.0-20240506185415-9bf2ced13842 // indirect
	golang.org/x/sys v0.20.0 // indirect
)
